//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoniz.shop.ReadModel.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public System.Guid Id { get; set; }
        public string PostalCode { get; set; }
        public string AddressLine { get; set; }
        public int CityId { get; set; }
        public System.Guid CustomerId { get; set; }
        public string Celphone { get; set; }
        public string Coordinate { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
